apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels: { app: user }
  template:
    metadata:
      labels: { app: user }
    spec:
      containers:
      - name: user-service
        image: docker pull proxykitten/user-service:v1
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "192.168.14.148"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "base"