apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: proxykitten/service-a:latest  # build & load into cluster
        env:
        - name: DB_HOST
          value: "192.168.14.148"
        - name: DB_NAME
          value: "base"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASS
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        ports:
        - containerPort: 80